# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_detallecarro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
